FROM ubuntu:latest

LABEL maintainer="Alrik Firl afirlortwo@gmail.com" \
      version="0.1" \
      description="DeityTD Ceed Dockerfile"

# Update packages
RUN apt-get update --fix-missing

# Install system tools / libraries
RUN apt-get -y install build-essential \
    ssh \
    sudo \
    vim \
    git \
    wget \
    make \
    cmake \
    virt-viewer \
    ffmpeg \
    libboost-all-dev \
    libopencv-dev \ 
    libois-dev \
    libogre-1.9-dev 

# Build tools
RUN sudo apt-get -y install gcc g++
RUN sudo apt-get -y install mercurial cmake-data cmake scons make ccache

# Cegui deps
RUN sudo apt-get -y install libfreetype6-dev libsilly-dev libxml2-dev libexpat1-dev libglfw-dev libglew-dev libglm-dev libgl1-mesa-glx libgl1-mesa-dri

# Ceed deps
RUN sudo apt-get -y install python python-pyside pyside-tools python-opengl libboost-python-dev

#(userid): id -u alrik --> 1000, (groupid): id -g  alrik--> 1000 (this presumably has to be changed if not the 1st user on the system?)
RUN export uid=1000 gid=1000 devname=ceed-user && \
    mkdir -p /home/${devname} && \
    echo "${devname}:x:${uid}:${gid}:Developer,,,:/home/${devname}:/bin/bash" >> /etc/passwd && \
    echo "${devname}:x:${uid}:" >> /etc/group && \
    touch /etc/sudoers.d/${devname} && \
    echo "${devname} ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/${devname} && \
    chmod 0440 /etc/sudoers.d/${devname} && \
    chown ${uid}:${gid} -R /home/${devname} && \
    mkdir -p /home/ceed-user && \
    chmod 7777 -R /home/ceed-user

#RUN useradd -s /bin/bash ceed-user
USER ceed-user 
ENV HOME /home/ceed-user
WORKDIR /home/ceed-user

COPY setup-ceed.sh setup-ceed.sh
RUN sudo chmod 7777 -R /home/ceed-user

# Clone ceed, cegui Repositories
RUN hg clone https://bitbucket.org/cegui/cegui
RUN hg clone https://bitbucket.org/cegui/ceed
RUN cd cegui; hg update v0-8; cd ..
RUN cd ceed; hg update v0-8; cd ..

# Enable additional output from Launcher
ENV QT_VERBOSE true
ENV QT_TESTING true

# Xvfb
ENV DISPLAY :99

ENTRYPOINT /bin/bash
#ENTRYPOINT ./setup-ceed.sh; /bin/bash
