FROM ubuntu:latest

LABEL maintainer="Alrik Firl afirlortwo@gmail.com" \
      version="0.1" \
      description="DeityTD Ceed Dockerfile"

# Update packages
RUN apt-get update --fix-missing

# Install system tools / libraries
RUN apt-get -y install build-essential \
    ssh \
    sudo \
    vim \
    git \
    wget \
    make \
    cmake \
    virt-viewer \
    ffmpeg \
    libboost-all-dev \
    libopencv-dev \ 
    libois-dev

# Build tools
RUN apt-get update --fix-missing && apt-get --fix-missing -y install \
	gcc \
    g++ \
    mercurial \
    cmake-data \
    cmake \
    scons \
    make \
    ccache

# Cegui deps
RUN apt-get update --fix-missing && apt-get --fix-missing -y install \
    libfreetype6-dev \
	libsilly-dev \
	libxml2-dev \
	libexpat1-dev \
	libglfw-dev \
	libglew-dev \
	libglm-dev \
	libgl1-mesa-glx \
	libgl1-mesa-dri \ 
	libxt-dev \ 
	libxaw7-dev

# Ceed deps
RUN apt-get update --fix-missing && apt-get --fix-missing -y install \
	python \
    python-pyside \
    pyside-tools \
    python-opengl \
    libboost-python-dev

#(userid): id -u alrik --> 1000, (groupid): id -g  alrik--> 1000 (this presumably has to be changed if not the 1st user on the system?)
RUN export uid=1000 gid=1000 devname=ceed-user && \
    mkdir -p /home/${devname} && \
    echo "${devname}:x:${uid}:${gid}:Developer,,,:/home/${devname}:/bin/bash" >> /etc/passwd && \
    echo "${devname}:x:${uid}:" >> /etc/group && \
    touch /etc/sudoers.d/${devname} && \
    echo "${devname} ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/${devname} && \
    chmod 0440 /etc/sudoers.d/${devname} && \
    chown ${uid}:${gid} -R /home/${devname} && \
    mkdir -p /home/ceed-user && \
    chmod 7777 -R /home/ceed-user

#RUN useradd -s /bin/bash ceed-user
USER ceed-user 
ENV HOME /home/ceed-user
WORKDIR /home/ceed-user

COPY setup-ceed.sh setup-ceed.sh
RUN sudo chmod 7777 -R /home/ceed-user

# Clone ceed, cegui Repositories
RUN hg clone https://bitbucket.org/cegui/cegui -u v0-8
RUN hg clone https://bitbucket.org/cegui/ceed -u v0-8
RUN hg clone https://bitbucket.org/sinbad/ogre/ -u v1-9
COPY resources/ogre-find-patch.diff cegui/.

RUN mkdir ogre/build && cd ogre/build && cmake .. && make -j2 && sudo make install
RUN cd cegui && hg import ogre-find-patch.diff --no-commit
RUN mkdir cegui/build && cd cegui/build && cmake .. && make -j2 && sudo make install

# Enable additional output from Launcher
ENV QT_VERBOSE true
ENV QT_TESTING true

# Xvfb
ENV DISPLAY :99

ENTRYPOINT /bin/bash
#ENTRYPOINT ./setup-ceed.sh; /bin/bash
